package javaproject;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;


/**
 *
 * @author akkal
 */
public class ClassProject extends javax.swing.JFrame {

    private DefaultTableModel model;
    
    // JDBC driver name and database URL
    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
    static final String DB_URL = "jdbc:mysql://localhost/";

    //  Database credentials
    static final String USER = "root";
    static final String PASS = "root";
    static final String DATABASE = "registration";
   
    private Connection jConnection = null;
    private Statement jStatement = null;
    /**
     * Creates new form ClassProject
     */
    public ClassProject() {
        initComponents();
        model = new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    
                },
                new String[] {
                    "Name", "Roll No", "Class"
                }
                
        );
        tblData.setModel(model);
        
        try{
            Class.forName(JDBC_DRIVER);
            jConnection = DriverManager.getConnection(DB_URL + DATABASE, USER, PASS);
            jStatement = jConnection.createStatement();
            
            String sql = "SELECT * FROM students";
            ResultSet rs = jStatement.executeQuery(sql);
            
            while(rs.next()){
//                int id  = rs.getInt("id");
                String name = rs.getString("name");
                String rollno = rs.getString("roll");
                String classno = rs.getString("class");

                model.addRow(new Object[]{ name, rollno, classno});
            }
            
            rs.close();
            jStatement.close();
            jConnection.close();
        }catch(SQLException se){
            //Handle errors for JDBC
            se.printStackTrace();
        }catch(Exception e){
            //Handle errors for Class.forName
            e.printStackTrace();
        }finally{
            //finally block used to close resources
            try{
                if(jStatement != null)
                    jStatement.close();
                
            } catch(SQLException se2){

            }// nothing we can do
            try{
                if(jConnection != null)
                    jConnection.close();
                
            }catch(SQLException se){
                se.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        classField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        rollField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        removeButton = new javax.swing.JButton();
        saveDetail = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel1.setText("Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 25, 80, 29));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel2.setText("Roll No:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 73, 80, 29));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel3.setText("Password:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 177, 80, 38));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel4.setText("Class:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 121, 80, 29));

        classField.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jPanel1.add(classField, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 115, 223, 42));

        nameField.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 19, 223, 42));

        rollField.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        rollField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollFieldActionPerformed(evt);
            }
        });
        jPanel1.add(rollField, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 67, 223, 42));

        passwordField.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 169, 223, 42));

        tblData.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Roll No", "Class", "Password"
            }
        ));
        jScrollPane1.setViewportView(tblData);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 0, 647, 262));

        removeButton.setFont(new java.awt.Font("Ubuntu", 3, 14)); // NOI18N
        removeButton.setText("Delete");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(removeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 233, 102, -1));

        saveDetail.setFont(new java.awt.Font("Ubuntu", 3, 14)); // NOI18N
        saveDetail.setText("Insert");
        saveDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDetailActionPerformed(evt);
            }
        });
        jPanel1.add(saveDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 233, 98, -1));

        updateButton.setFont(new java.awt.Font("Ubuntu", 3, 14)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 233, 103, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void rollFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollFieldActionPerformed

    private void saveDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDetailActionPerformed
        // TODO add your handling code here:
  
        try{
            Class.forName("com.mysql.jdbc.Driver");
            jConnection = DriverManager.getConnection(DB_URL + DATABASE, USER, PASS);
            jStatement = jConnection.createStatement();
            
            String name = nameField.getText();
            String rollno = rollField.getText();
            String classno = classField.getText();
            
            
            
            String sql = "INSERT INTO students(name,roll,class,password) VALUES('" + name + "','" + rollno +"','" + classno + "','')";
            int result = jStatement.executeUpdate(sql);
            if(result > 0){
                Object data[] = new Object[]{name, rollno, classno};

                model.addRow(data);
                clearForm();
            }
            
            jStatement.close();
            jConnection.close();
        }catch(SQLException se){
            //Handle errors for JDBC
            se.printStackTrace();
        }catch(Exception e){
            //Handle errors for Class.forName
            e.printStackTrace();
        }finally{
            //finally block used to close resources
            try{
                if(jStatement != null)
                    jStatement.close();
                
            } catch(SQLException se2){

            }// nothing we can do
            try{
                if(jConnection != null)
                    jConnection.close();
                
            }catch(SQLException se){
                se.printStackTrace();
            }
        }
        
       
    }//GEN-LAST:event_saveDetailActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
        
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure ?", "Warning", dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
            if(tblData.getSelectedRow() != -1){
                try{
                    Class.forName("com.mysql.jdbc.Driver");
                    jConnection = DriverManager.getConnection(DB_URL + DATABASE, USER, PASS);
                    jStatement = jConnection.createStatement();
                    
                    int row = tblData.getSelectedRow();
                    String name = model.getValueAt(row, 0).toString();
                    
                    String sql = "DELETE FROM students WHERE name='" + name+"'";
                    
                    int result = jStatement.executeUpdate(sql);
                    if(result > 0){
                        model.removeRow(row);
                    
                    }
                    
                    jStatement.close();
                    jConnection.close();
                }catch(SQLException se){
                    //Handle errors for JDBC
                    se.printStackTrace();
                }catch(Exception e){
                    //Handle errors for Class.forName
                    e.printStackTrace();
                }finally{
                    //finally block used to close resources
                    try{
                        if(jStatement != null)
                            jStatement.close();

                    } catch(SQLException se2){

                    }// nothing we can do
                    try{
                        if(jConnection != null)
                            jConnection.close();

                    }catch(SQLException se){
                        se.printStackTrace();
                    }
                }
                
            }
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed

        
//       try {
//           
//            String name = nameField.getText();
//            String rollno = rollField.getText();
//            String classno = classField.getText();
//            
//       }



//String sql = "update dataop set id='"+val1+"',username='"
//            +val2+"',password='"+val3+"',age='"
//            +val4+"',email='"
//            +val5+"' where id='"
//            +val1+"'";
//pst=connect.prepareStatement(sql);
//pst.execute();
//JOptionPane.showMessageDialog(null, "has been Updated !");
//        } catch (SQLException | HeadlessException e) 
//        {
//JOptionPane.showMessageDialog(null, e);
//        }

        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_updateButtonActionPerformed

     private void clearForm(){
        nameField.setText("");
        rollField.setText("");
        classField.setText("");
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClassProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField classField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField passwordField;
    private javax.swing.JButton removeButton;
    private javax.swing.JTextField rollField;
    private javax.swing.JButton saveDetail;
    private javax.swing.JTable tblData;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
